### PR TITLE
Add notification channels

### PR DESCRIPTION
**Pull request by nikodemas**
I have added notification channels section into the `find` command. However, I still haven't updated the [index functions](https://github.com/panodata/grafana-wtf/blob/main/grafana_wtf/core.py#L612-L661), so my issue is still not solved with this PR as the notification channels are not being attached to the dashboards. Therefore, marking this as draft till I update the index part.

### CODE REVIEW

**Comment by nikodemas** [comment]
@amotl I just realized that unlike as it is for the data sources, where the full name of the data source is presented in the dashboard, alert channels are presented only by their `uid`. Also, with the alerting in Grafana [being unified in the version 8](https://grafana.com/blog/2021/06/14/the-new-unified-alerting-system-for-grafana-everything-you-need-to-know/) the alerting system differs quite a bit across the different versions. Finally, notification channels (or contact points) do not seem to be important enough to be a default printout for the `find` command. For these reasons, I will revert most of the changes in this PR and will keep only the minimal version of changes and I think that the issue https://github.com/panodata/grafana-wtf/issues/82 can be closed.

**Comment by nikodemas** [comment]
So basically this PR doesn't differ anymore from the https://github.com/panodata/grafana-wtf/pull/105 except for the changes in `grafana_wtf/report/textual.py` which are completely unrelated to the notification channels - I just noticed that there is a bug in the textual output as data sources get a prefix of `Dashboard` instead of `Data Source`. I guess we could rename this PR or I could close this PR and create a new one only for this change. Let me know what you think.

**Comment by amotl** [comment]
Dear @nikodemas,

thank you for making progress on this. If you trimmed down your patch, and the outcome is just an unrelated fix, I am humbly asking you to hand in a separate PR.

Thanks a stack and with kind regards,
Andreas.

**Comment by nikodemas** [comment]
Yes, I am closing it. Thanks for the reminder!

**Pull request closed without merging**
